// Single User Data Type
export const SINGLE_USER_DATA_REDUCER = "SINGLE_USER_DATA_REDUCER";
export const SINGLE_USER_DATA_SUCCESS = "SINGLE_USER_DATA_SUCCESS";
export const SINGLE_USER_DATA_FAIL = "SINGLE_USER_DATA_FAIL";

// Login User Data
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

// Login User Data
export const ALL_EMPLOYEE_DATA_REQUEST = "ALL_EMPLOYEE_DATA_REQUEST";
export const ALL_EMPLOYEE_DATA_SUCCESS = "ALL_EMPLOYEE_DATA_SUCCESS";
export const ALL_EMPLOYEE_DATA_FAIL = "ALL_EMPLOYEE_DATA_FAIL";

// Apply leave post api
export const POST_LEAVE_APPLY_BY_EMPLOYEE_REQUEST = "POST_LEAVE_APPLY_BY_EMPLOYEE_REQUEST";
export const POST_LEAVE_APPLY_BY_EMPLOYEE_SUCCESS = "POST_LEAVE_APPLY_BY_EMPLOYEE_SUCCESS";
export const POST_LEAVE_APPLY_BY_EMPLOYEE_FAIL = "POST_LEAVE_APPLY_BY_EMPLOYEE_FAIL";

// Apply attendance leave 
export const GET_ATTENDANCE_LOGS_OF_EMPLOYEES_REQUEST = "GET_ATTENDANCE_LOGS_OF_EMPLOYEES_REQUEST";
export const GET_ATTENDANCE_LOGS_OF_EMPLOYEES_SUCCESS = "GET_ATTENDANCE_LOGS_OF_EMPLOYEES_SUCCESS";
export const GET_ATTENDANCE_LOGS_OF_EMPLOYEES_FAIL = "GET_ATTENDANCE_LOGS_OF_EMPLOYEES_FAIL";

// Employee leave status
export const GET_EMPLOYEE_LEAVE_STATUS_REQUEST = "GET_EMPLOYEE_LEAVE_STATUS_REQUEST";
export const GET_EMPLOYEE_LEAVE_STATUS_SUCCESS = "GET_EMPLOYEE_LEAVE_STATUS_SUCCESS";
export const GET_EMPLOYEE_LEAVE_STATUS_FAIL = "GET_EMPLOYEE_LEAVE_STATUS_FAIL";

// Employee Hilidays Status
export const GET_HOLIDAYS_DATA_REQUEST = "GET_HOLIDAYS_DATA_REQUEST";
export const GET_HOLIDAYS_DATA_SUCCESS = "GET_HOLIDAYS_DATA_SUCCESS";
export const GET_HOLIDAYS_DATA_FAIL = "GET_HOLIDAYS_DATA_FAIL";

// Employee Hilidays Status
export const GET_LEAVE_REQUEST_REQUEST = "GET_LEAVE_REQUEST_REQUEST";
export const GET_LEAVE_REQUEST_SUCCESS = "GET_LEAVE_REQUEST_SUCCESS";
export const GET_LEAVE_REQUEST_FAIL = "GET_LEAVE_REQUEST_FAIL";

// Employee Hilidays Status
export const POST_LEAVE_REQUEST_REQUEST = "POST_LEAVE_REQUEST_REQUEST";
export const POST_LEAVE_REQUEST_SUCCESS = "POST_LEAVE_REQUEST_SUCCESS";
export const POST_LEAVE_REQUEST_FAIL = "POST_LEAVE_REQUEST_FAIL";

// Employee Hilidays Status
export const POST_APPLY_REGULARIZE_REQUEST = "POST_APPLY_REGULARIZE_REQUEST";
export const POST_APPLY_REGULARIZE_SUCCESS = "POST_APPLY_REGULARIZE_SUCCESS";
export const POST_APPLY_REGULARIZE_FAIL = "POST_APPLY_REGULARIZE_FAIL";

export const PUT_LEAVE_APPROVAL_BY_MANAGER_REQUEST = "PUT_LEAVE_APPROVAL_BY_MANAGER_REQUEST";
export const PUT_LEAVE_APPROVAL_BY_MANAGER_SUCCESS = "PUT_LEAVE_APPROVAL_BY_MANAGER_SUCCESS";
export const PUT_LEAVE_APPROVAL_BY_MANAGER_FAIL = "PUT_LEAVE_APPROVAL_BY_MANAGER_FAIL";

// Generate compoff leave
export const POST_APPLY_COMPOFF_LEAVE_REQUEST = "POST_APPLY_COMPOFF_LEAVE_REQUEST";
export const POST_APPLY_COMPOFF_LEAVE_SUCCESS = "POST_APPLY_COMPOFF_LEAVE_SUCCESS";
export const POST_APPLY_COMPOFF_LEAVE_FAIL = "POST_APPLY_COMPOFF_LEAVE_FAIL";

// Pending leave approval
export const GET_COMPOFF_LEAVE_APPROVAL_REQUEST = "GET_COMPOFF_LEAVE_APPROVAL_REQUEST";
export const GET_COMPOFF_LEAVE_APPROVAL_SUCCESS = "GET_COMPOFF_LEAVE_APPROVAL_SUCCESS";
export const GET_COMPOFF_LEAVE_APPROVAL_FAIL = "GET_COMPOFF_LEAVE_APPROVAL_FAIL";

export const PUT_COMPOFF_LEAVE_STATUS_REQUEST = "PUT_COMPOFF_LEAVE_STATUS_REQUEST";
export const PUT_COMPOFF_LEAVE_STATUS_SUCCESS = "PUT_COMPOFF_LEAVE_STATUS_SUCCESS";
export const PUT_COMPOFF_LEAVE_STATUS_FAIL = "PUT_COMPOFF_LEAVE_STATUS_FAIL";

export const POST_MEDICAL_FILE_REQUEST = "POST_MEDICAL_FILE_REQUEST";
export const POST_MEDICAL_FILE_SUCCESS = "POST_MEDICAL_FILE_SUCCESS";
export const POST_MEDICAL_FILE_FAIL = "POST_MEDICAL_FILE_FAIL";

export const DELETE_LEAVE_REQUEST_REQUEST = "DELETE_LEAVE_REQUEST_REQUEST";
export const DELETE_LEAVE_REQUEST_SUCCESS = "DELETE_LEAVE_REQUEST_SUCCESS";
export const DELETE_LEAVE_REQUEST_FAIL = "DELETE_LEAVE_REQUEST_FAIL";

export const GET_PUBLIC_DOCUMENTS_REQUEST = "GET_PUBLIC_DOCUMENTS_REQUEST";
export const GET_PUBLIC_DOCUMENTS_SUCCESS = "GET_PUBLIC_DOCUMENTS_SUCCESS";
export const GET_PUBLIC_DOCUMENTS_FAIL = "GET_PUBLIC_DOCUMENTS_FAIL";

export const GET_COMPOFF_DATA_REQUEST = "GET_COMPOFF_DATA_REQUEST";
export const GET_COMPOFF_DATA_SUCCESS = "GET_COMPOFF_DATA_SUCCESS";
export const GET_COMPOFF_DATA_FAIL = "GET_COMPOFF_DATA_FAIL";

export const GET_TEAMMATE_DATA_REQUEST = "GET_TEAMMATE_DATA_REQUEST";
export const GET_TEAMMATE_DATA_SUCCESS = "GET_TEAMMATE_DATA_SUCCESS";
export const GET_TEAMMATE_DATA_FAIL = "GET_TEAMMATE_DATA_FAIL";

export const GET_EMPLOYEE_PRIVATE_DOC_REQUEST = "GET_EMPLOYEE_PRIVATE_DOC_REQUEST";
export const GET_EMPLOYEE_PRIVATE_DOC_SUCCESS = "GET_EMPLOYEE_PRIVATE_DOC_SUCCESS";
export const GET_EMPLOYEE_PRIVATE_DOC_FAIL = "GET_EMPLOYEE_PRIVATE_DOC_FAIL";

export const PROFILE_IMAGE_UPDATE_REQUEST = "PROFILE_IMAGE_UPDATE_REQUEST";
export const PROFILE_IMAGE_UPDATE_SUCCESS = "PROFILE_IMAGE_UPDATE_SUCCESS";
export const PROFILE_IMAGE_UPDATE_FAIL = "PROFILE_IMAGE_UPDATE_FAIL";

export const POST_SEND_OTP_WITH_EMAIL_REQUEST = "POST_SEND_OTP_WITH_EMAIL_REQUEST";
export const POST_SEND_OTP_WITH_EMAIL_SUCCESS = "POST_SEND_OTP_WITH_EMAIL_SUCCESS";
export const POST_SEND_OTP_WITH_EMAIL_FAIL = "POST_SEND_OTP_WITH_EMAIL_FAIL";

export const POST_OTP_VERIFICATION_REQUEST = "POST_OTP_VERIFICATION_REQUEST";
export const POST_OTP_VERIFICATION_SUCCESS = "POST_OTP_VERIFICATION_SUCCESS";
export const POST_OTP_VERIFICATION_FAIL = "POST_OTP_VERIFICATION_FAIL";

export const POST_CONFIRM_PASSWORD_REQUEST = "POST_CONFIRM_PASSWORD_REQUEST";
export const POST_CONFIRM_PASSWORD_SUCCESS = "POST_CONFIRM_PASSWORD_SUCCESS";
export const POST_CONFIRM_PASSWORD_FAIL = "POST_CONFIRM_PASSWORD_FAIL";

export const POST_PROFILE_IMAGE_UPLOAD_REQUEST = "POST_PROFILE_IMAGE_UPLOAD_REQUEST";
export const POST_PROFILE_IMAGE_UPLOAD_SUCCESS = "POST_PROFILE_IMAGE_UPLOAD_SUCCESS";
export const POST_PROFILE_IMAGE_UPLOAD_FAIL = "POST_PROFILE_IMAGE_UPLOAD_FAIL";

export const GET_CALENDER_LOGS_API_REQUEST = "GET_CALENDER_LOGS_API_REQUEST";
export const GET_CALENDER_LOGS_API_SUCCESS = "GET_CALENDER_LOGS_API_SUCCESS";
export const GET_CALENDER_LOGS_API_FAIL = "GET_CALENDER_LOGS_API_FAIL";

export const GET_ALL_EMPLOYEE_ATTENDANCE_REQUEST = "GET_ALL_EMPLOYEE_ATTENDANCE_REQUEST";
export const GET_ALL_EMPLOYEE_ATTENDANCE_SUCCESS = "GET_ALL_EMPLOYEE_ATTENDANCE_SUCCESS";
export const GET_ALL_EMPLOYEE_ATTENDANCE_FAIL = "GET_ALL_EMPLOYEE_ATTENDANCE_FAIL";